// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: positions.proto

package positionspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AddPositionsService_AddPositions_FullMethodName = "/positions.AddPositionsService/AddPositions"
)

// AddPositionsServiceClient is the client API for AddPositionsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AddPositionsServiceClient interface {
	AddPositions(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type addPositionsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAddPositionsServiceClient(cc grpc.ClientConnInterface) AddPositionsServiceClient {
	return &addPositionsServiceClient{cc}
}

func (c *addPositionsServiceClient) AddPositions(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, AddPositionsService_AddPositions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddPositionsServiceServer is the server API for AddPositionsService service.
// All implementations must embed UnimplementedAddPositionsServiceServer
// for forward compatibility.
type AddPositionsServiceServer interface {
	AddPositions(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedAddPositionsServiceServer()
}

// UnimplementedAddPositionsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAddPositionsServiceServer struct{}

func (UnimplementedAddPositionsServiceServer) AddPositions(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method AddPositions not implemented")
}
func (UnimplementedAddPositionsServiceServer) mustEmbedUnimplementedAddPositionsServiceServer() {}
func (UnimplementedAddPositionsServiceServer) testEmbeddedByValue()                             {}

// UnsafeAddPositionsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AddPositionsServiceServer will
// result in compilation errors.
type UnsafeAddPositionsServiceServer interface {
	mustEmbedUnimplementedAddPositionsServiceServer()
}

func RegisterAddPositionsServiceServer(s grpc.ServiceRegistrar, srv AddPositionsServiceServer) {
	// If the following call panics, it indicates UnimplementedAddPositionsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AddPositionsService_ServiceDesc, srv)
}

func _AddPositionsService_AddPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddPositionsServiceServer).AddPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AddPositionsService_AddPositions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddPositionsServiceServer).AddPositions(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// AddPositionsService_ServiceDesc is the grpc.ServiceDesc for AddPositionsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AddPositionsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "positions.AddPositionsService",
	HandlerType: (*AddPositionsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPositions",
			Handler:    _AddPositionsService_AddPositions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "positions.proto",
}
