// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: positions.proto

package positionspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Position struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Barcode         string                 `protobuf:"bytes,1,opt,name=barcode,proto3" json:"barcode,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UnitMeasurement string                 `protobuf:"bytes,3,opt,name=unit_measurement,json=unitMeasurement,proto3" json:"unit_measurement,omitempty"`
	Quantity        float64                `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	PriceBuy        float64                `protobuf:"fixed64,5,opt,name=price_buy,json=priceBuy,proto3" json:"price_buy,omitempty"`
	PriceSell       float64                `protobuf:"fixed64,6,opt,name=price_sell,json=priceSell,proto3" json:"price_sell,omitempty"`
	Date            *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_positions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_positions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_positions_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

func (x *Position) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Position) GetUnitMeasurement() string {
	if x != nil {
		return x.UnitMeasurement
	}
	return ""
}

func (x *Position) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Position) GetPriceBuy() float64 {
	if x != nil {
		return x.PriceBuy
	}
	return 0
}

func (x *Position) GetPriceSell() float64 {
	if x != nil {
		return x.PriceSell
	}
	return 0
}

func (x *Position) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*Position            `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_positions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_positions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_positions_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_positions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_positions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_positions_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_positions_proto protoreflect.FileDescriptor

const file_positions_proto_rawDesc = "" +
	"\n" +
	"\x0fpositions.proto\x12\tpositions\x1a\x1fgoogle/protobuf/timestamp.proto\"\xeb\x01\n" +
	"\bPosition\x12\x18\n" +
	"\abarcode\x18\x01 \x01(\tR\abarcode\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12)\n" +
	"\x10unit_measurement\x18\x03 \x01(\tR\x0funitMeasurement\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\x12\x1b\n" +
	"\tprice_buy\x18\x05 \x01(\x01R\bpriceBuy\x12\x1d\n" +
	"\n" +
	"price_sell\x18\x06 \x01(\x01R\tpriceSell\x12.\n" +
	"\x04date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x04date\"<\n" +
	"\aRequest\x121\n" +
	"\tpositions\x18\x01 \x03(\v2\x13.positions.PositionR\tpositions\"\x1c\n" +
	"\bResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg2N\n" +
	"\x13AddPositionsService\x127\n" +
	"\fAddPositions\x12\x12.positions.Request\x1a\x13.positions.ResponseB\x1eZ\x1cproto/accounting/positionspbb\x06proto3"

var (
	file_positions_proto_rawDescOnce sync.Once
	file_positions_proto_rawDescData []byte
)

func file_positions_proto_rawDescGZIP() []byte {
	file_positions_proto_rawDescOnce.Do(func() {
		file_positions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_positions_proto_rawDesc), len(file_positions_proto_rawDesc)))
	})
	return file_positions_proto_rawDescData
}

var file_positions_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_positions_proto_goTypes = []any{
	(*Position)(nil),              // 0: positions.Position
	(*Request)(nil),               // 1: positions.Request
	(*Response)(nil),              // 2: positions.Response
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_positions_proto_depIdxs = []int32{
	3, // 0: positions.Position.date:type_name -> google.protobuf.Timestamp
	0, // 1: positions.Request.positions:type_name -> positions.Position
	1, // 2: positions.AddPositionsService.AddPositions:input_type -> positions.Request
	2, // 3: positions.AddPositionsService.AddPositions:output_type -> positions.Response
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_positions_proto_init() }
func file_positions_proto_init() {
	if File_positions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_positions_proto_rawDesc), len(file_positions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_positions_proto_goTypes,
		DependencyIndexes: file_positions_proto_depIdxs,
		MessageInfos:      file_positions_proto_msgTypes,
	}.Build()
	File_positions_proto = out.File
	file_positions_proto_goTypes = nil
	file_positions_proto_depIdxs = nil
}
